# Generated by Django 4.0.5 on 2022-06-12 07:18

import autoslug.fields
from django.db import migrations, models
import pidtuningtool.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuner_user', models.CharField(default='anonymous', help_text='Session Key', max_length=200)),
                ('url_ref', autoslug.fields.AutoSlugField(editable=False, populate_from='tuner_user', slugify=pidtuningtool.models.default_random_slug, unique=True)),
                ('plant_creation', models.DateTimeField(auto_now_add=True)),
                ('plant_params', models.JSONField(default=pidtuningtool.models.default_empty_json, editable=False)),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
            },
        ),
    ]
