%DO NOT EDIT, autogenerated with g_PID_combinations.sh
if 1 && PI_Ms_1_4_enable && PI_Ms_2_0_enable && PID_Ms_1_4_enable && PID_Ms_2_0_enable
  %% Respuestas de ambos sistemas
  plot(X1_t,X1,X2_t,X2,X3_t,X3,X4_t,X4,t,R,t,D);
  xlabel('Time (s)');
  ylabel('Magnitude (%)')
  legend('PI 1.4','PI 2.0','PID 1.4','PID 2.0','|R(s)|=15%','|D(s)|=5%','Location','southeast');

  % Save the image
  print(output_path+"ABCDRD.png",'-dpng')
  fprintf('Image ready\n')

end

if 1 && PI_Ms_1_4_enable && PI_Ms_2_0_enable && PID_Ms_1_4_enable
  %% Respuestas de ambos sistemas
  plot(X1_t,X1,X2_t,X2,X3_t,X3,t,R,t,D);
  xlabel('Time (s)');
  ylabel('Magnitude (%)')
  legend('PI 1.4','PI 2.0','PID 1.4','|R(s)|=15%','|D(s)|=5%','Location','southeast');

  % Save the image
  print(output_path+"ABCRD.png",'-dpng')
  fprintf('Image ready\n')

end

if 1 && PI_Ms_1_4_enable && PI_Ms_2_0_enable && PID_Ms_2_0_enable
  %% Respuestas de ambos sistemas
  plot(X1_t,X1,X2_t,X2,X4_t,X4,t,R,t,D);
  xlabel('Time (s)');
  ylabel('Magnitude (%)')
  legend('PI 1.4','PI 2.0','PID 2.0','|R(s)|=15%','|D(s)|=5%','Location','southeast');

  % Save the image
  print(output_path+"ABDRD.png",'-dpng')
  fprintf('Image ready\n')

end

if 1 && PI_Ms_1_4_enable && PI_Ms_2_0_enable
  %% Respuestas de ambos sistemas
  plot(X1_t,X1,X2_t,X2,t,R,t,D);
  xlabel('Time (s)');
  ylabel('Magnitude (%)')
  legend('PI 1.4','PI 2.0','|R(s)|=15%','|D(s)|=5%','Location','southeast');

  % Save the image
  print(output_path+"ABRD.png",'-dpng')
  fprintf('Image ready\n')

end

if 1 && PI_Ms_1_4_enable && PID_Ms_1_4_enable && PID_Ms_2_0_enable
  %% Respuestas de ambos sistemas
  plot(X1_t,X1,X3_t,X3,X4_t,X4,t,R,t,D);
  xlabel('Time (s)');
  ylabel('Magnitude (%)')
  legend('PI 1.4','PID 1.4','PID 2.0','|R(s)|=15%','|D(s)|=5%','Location','southeast');

  % Save the image
  print(output_path+"ACDRD.png",'-dpng')
  fprintf('Image ready\n')

end

if 1 && PI_Ms_1_4_enable && PID_Ms_1_4_enable
  %% Respuestas de ambos sistemas
  plot(X1_t,X1,X3_t,X3,t,R,t,D);
  xlabel('Time (s)');
  ylabel('Magnitude (%)')
  legend('PI 1.4','PID 1.4','|R(s)|=15%','|D(s)|=5%','Location','southeast');

  % Save the image
  print(output_path+"ACRD.png",'-dpng')
  fprintf('Image ready\n')

end

if 1 && PI_Ms_1_4_enable && PID_Ms_2_0_enable
  %% Respuestas de ambos sistemas
  plot(X1_t,X1,X4_t,X4,t,R,t,D);
  xlabel('Time (s)');
  ylabel('Magnitude (%)')
  legend('PI 1.4','PID 2.0','|R(s)|=15%','|D(s)|=5%','Location','southeast');

  % Save the image
  print(output_path+"ADRD.png",'-dpng')
  fprintf('Image ready\n')

end

if 1 && PI_Ms_1_4_enable
  %% Respuestas de ambos sistemas
  plot(X1_t,X1,t,R,t,D);
  xlabel('Time (s)');
  ylabel('Magnitude (%)')
  legend('PI 1.4','|R(s)|=15%','|D(s)|=5%','Location','southeast');

  % Save the image
  print(output_path+"ARD.png",'-dpng')
  fprintf('Image ready\n')

end

if 1 && PI_Ms_2_0_enable && PID_Ms_1_4_enable && PID_Ms_2_0_enable
  %% Respuestas de ambos sistemas
  plot(X2_t,X2,X3_t,X3,X4_t,X4,t,R,t,D);
  xlabel('Time (s)');
  ylabel('Magnitude (%)')
  legend('PI 2.0','PID 1.4','PID 2.0','|R(s)|=15%','|D(s)|=5%','Location','southeast');

  % Save the image
  print(output_path+"BCDRD.png",'-dpng')
  fprintf('Image ready\n')

end

if 1 && PI_Ms_2_0_enable && PID_Ms_1_4_enable
  %% Respuestas de ambos sistemas
  plot(X2_t,X2,X3_t,X3,t,R,t,D);
  xlabel('Time (s)');
  ylabel('Magnitude (%)')
  legend('PI 2.0','PID 1.4','|R(s)|=15%','|D(s)|=5%','Location','southeast');

  % Save the image
  print(output_path+"BCRD.png",'-dpng')
  fprintf('Image ready\n')

end

if 1 && PI_Ms_2_0_enable && PID_Ms_2_0_enable
  %% Respuestas de ambos sistemas
  plot(X2_t,X2,X4_t,X4,t,R,t,D);
  xlabel('Time (s)');
  ylabel('Magnitude (%)')
  legend('PI 2.0','PID 2.0','|R(s)|=15%','|D(s)|=5%','Location','southeast');

  % Save the image
  print(output_path+"BDRD.png",'-dpng')
  fprintf('Image ready\n')

end

if 1 && PI_Ms_2_0_enable
  %% Respuestas de ambos sistemas
  plot(X2_t,X2,t,R,t,D);
  xlabel('Time (s)');
  ylabel('Magnitude (%)')
  legend('PI 2.0','|R(s)|=15%','|D(s)|=5%','Location','southeast');

  % Save the image
  print(output_path+"BRD.png",'-dpng')
  fprintf('Image ready\n')

end

if 1 && PID_Ms_1_4_enable && PID_Ms_2_0_enable
  %% Respuestas de ambos sistemas
  plot(X3_t,X3,X4_t,X4,t,R,t,D);
  xlabel('Time (s)');
  ylabel('Magnitude (%)')
  legend('PID 1.4','PID 2.0','|R(s)|=15%','|D(s)|=5%','Location','southeast');

  % Save the image
  print(output_path+"CDRD.png",'-dpng')
  fprintf('Image ready\n')

end

if 1 && PID_Ms_1_4_enable
  %% Respuestas de ambos sistemas
  plot(X3_t,X3,t,R,t,D);
  xlabel('Time (s)');
  ylabel('Magnitude (%)')
  legend('PID 1.4','|R(s)|=15%','|D(s)|=5%','Location','southeast');

  % Save the image
  print(output_path+"CRD.png",'-dpng')
  fprintf('Image ready\n')

end

if 1 && PID_Ms_2_0_enable
  %% Respuestas de ambos sistemas
  plot(X4_t,X4,t,R,t,D);
  xlabel('Time (s)');
  ylabel('Magnitude (%)')
  legend('PID 2.0','|R(s)|=15%','|D(s)|=5%','Location','southeast');

  % Save the image
  print(output_path+"DRD.png",'-dpng')
  fprintf('Image ready\n')

end

if 1
  %% Respuestas de ambos sistemas
  plot(t,R,t,D);
  xlabel('Time (s)');
  ylabel('Magnitude (%)')
  legend('|R(s)|=15%','|D(s)|=5%','Location','southeast');

  % Save the image
  print(output_path+"RD.png",'-dpng')
  fprintf('Image ready\n')

end

