#!/bin/bash

V0=('t,X1,')
V1=('t,X2,')
V2=('t,X3,')
V3=('t,X4,')
V0_N=("'PI 1.4',")
V1_N=("'PI 2.0',")
V2_N=("'PID 1.4',")
V3_N=("'PID 2.0',")
I0_N=('A')
I1_N=('B')
I2_N=('C')
I3_N=('D')
EI0_N=(' && PI_Ms_1_4_enable')
EI1_N=(' && PI_Ms_2_0_enable')
EI2_N=(' && PID_Ms_1_4_enable')
EI3_N=(' && PID_Ms_2_0_enable')

echo "%DO NOT EDIT, autogenerated with $0"

for NUM0 in '0' '1'
do
    for NUM1 in '0' '1'
    do
	for NUM2 in '0' '1'
	do
	    for NUM3 in '0' '1'
	    do
		##
		printf 'if 1'"${EI0_N[$NUM0]}${EI1_N[$NUM1]}${EI2_N[$NUM2]}${EI3_N[$NUM3]}"
		for COND in 
		do
		    printf
		done
		echo "
  %% Respuestas de ambos sistemas
  plot(${V0[$NUM0]}${V1[$NUM1]}${V2[$NUM2]}${V3[$NUM3]}t,R,t,D);
  xlabel('Time (s)');
  ylabel('Magnitude (%)')
  legend(${V0_N[$NUM0]}${V1_N[$NUM1]}${V2_N[$NUM2]}${V3_N[$NUM3]}'|R(s)|=15%','|D(s)|=5%','Location','northwest');

  % Save the image
  print(output_path+"'"'"${I0_N[$NUM0]}${I1_N[$NUM1]}${I2_N[$NUM2]}${I3_N[$NUM3]}RD.png"'"'",'-dpng')
  fprintf('Image ready\n')

end
"

		##
	    done
	done
    done
done


exit 0
